### PR TITLE
csd: Camera definition file for Intel RealSense RGB colour camera

### PR DESCRIPTION
**Pull request by SaliniVenate**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Isn't this xml supposed to be generated dynamically?

**Comment by SaliniVenate** [comment]
Ideally camera definition file should be generated dynamically, but to start with, we'll have a static xml file.

**Comment by SaliniVenate** [comment]
https://github.com/01org/camera-streaming-daemon/pull/83

**Comment by lbegani** [comment]
Addressed in https://github.com/intel-aero/meta-intel-aero/pull/288, this PR can be closed

**Pull request closed without merging**
