### PR TITLE
Add dmidecode to image

### PR DESCRIPTION
**Pull request by padmashree9110**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
I'm writing the change to aero-get-version to apply this one

**Comment by avinash-palleti** [comment]
@lucasdemarchi Updated aero-get-version is submitted already on meta-intel-aero-base

**Comment by avinash-palleti** [comment]
Shall we submit new PR to master branch, earlier ones are on master-next

**Comment by lucasdemarchi** [comment]
When I apply I can change to master. But for new ones, yes... Should be on master.

**Comment by lucasdemarchi** [comment]
This is applied.

**Pull request closed without merging**
