### PR TITLE
Intel Aero v1.5.1

### PR DESCRIPTION
**Pull request by lucasdemarchi**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@avinash-palleti @anitha-suresh  can you check this on current master if network interfaces is setup correctly and if it matches the doc from https://intel-aero.github.io/getting-started/connecting/ ?

**Comment by anitha-suresh** [comment]
@lucasdemarchi , we checked the release image (yet to check on master) and below are the observations:
1: "After connecting to Aero it's advised to change the **passkey** and ssid": Passkey is missing in the statement
2: Configuration file: /etc/NetworkManager/system-connections/**Hostspot** :  To be modified to hotpost (which you are already aware of)
3: On changing from Station Mode to AP Mode: though type change (as AP mode) is being shown when checked, it is not exhibited when scanned and was OK after reboot. 
4: Also on changing the SSID, we could see the change in the config file happening but did not really take into effect, when we scanned and checked (did not show aero-1.5.1) and then was OK after reboot.

**Comment by anselmolsm** [comment]
@anitha-suresh The source of the doc is at https://github.com/intel-aero/intel-aero-docs/

**Comment by lucasdemarchi** [comment]
After the change to AP mode and ssid we need to add a `systemctl restart NetworkManager` or find a way to convince NM to apply the new settings without a restart.  Can you send a PR to fix the doc? It's on the link @anselmolsm provided above. Thanks.

**Comment by avinash-palleti** [comment]
@lucasdemarchi submitted PR with changes, i also added a note to restart networkmanager for new ssid to take effect.

https://github.com/intel-aero/intel-aero-docs/pull/9

**Pull request merged**
