### PR TITLE
csd:Enable SimpleHTTPServer

### PR DESCRIPTION
**Pull request by SaliniVenate**
HTTP Server is required for hosting the camera definition files, images and videos.

### CODE REVIEW

**Comment by avinash-palleti** [comment]
👍

**Comment by lucasdemarchi** [comment]
Is this for 1.5?

**Comment by SaliniVenate** [comment]
Yes Lucas.

**Comment by anitha-suresh** [comment]
This wasn't tagged for 1.5 release though.

**Comment by lucasdemarchi** [comment]
The only user of such a daemon would be CSD as far as I can see. Currently CSD is not updated to use that functionality and we are very close to releasing 1.5.

**Comment by lbegani** [comment]
The work on CSD is in progress, plan to submit initial changes asap. Also, the corresponding changes on QGC side is in progress, which means testing is still due. As I understood from Luis, whatever is ready can go in this release. Later, we can push further changes as update packages.

**Comment by SaliniVenate** [comment]
Fixed the path for hosting files. Changed it from /var/html to /var/http .

**Pull request merged**
