### PR TITLE
Enable SSH

### PR DESCRIPTION
**Pull request by padmashree9110**
Enabling SSH plugin.
Issue: #204 
Test: Verified by giving 127.0.0.1 as "connect to" on login page, this will get connect through SSH.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
should have a "cockpit: " prefix in the commit message.  Please also check if  you can upload ssh keys:

1. Upload ssh key via cockpit
1. Open the terminal in cockpit and set root password to something
1. Open a terminal (outside cockpit) and try to ssh into Aero
1. Check the new key is succesfully added to ~/.ssh/authorized_keys

**Comment by lucasdemarchi** [comment]
Btw, the functionality we want is the one above to add ssh keys for the users. If that's possible without the ssh plugin, then we don't need it.

**Comment by padmashree9110** [comment]
Purpose of the ssh plugin in the cockpit is to run the cockpit web interface on one server, and use that to maintain several other machines through ssh (on other machines we only need cockpit-bridge not web server). 
But if our requirement is only to add ssh keys for users, it's possible even without the ssh plugin. I verified the same.

**Comment by lucasdemarchi** [comment]
Ok, then we don't need this plugin. Thanks.

**Pull request closed without merging**
