### PR TITLE
Enable Apache server

### PR DESCRIPTION
**Pull request by SaliniVenate**
Enabling the Apache server to host the camera definition file.

### CODE REVIEW

**Comment by anselmolsm** [comment]
Do we need apache and all his glory to host a single file? I bet there are lighter (and simpler) options for that.

**Comment by lbegani** [comment]
@anselmolsm There will couple of them, any other option that you have in your mind ?

**Comment by lucasdemarchi** [comment]
To host a couple of files, even python's simplehttp server would do it. lighttpd is another option that may be even already installed due to dependencies.  And we could also integrate this with cockpit.

**Comment by lbegani** [comment]
@lucasdemarchi Thanks, we will try and use one of them after test.

**Comment by SaliniVenate** [comment]
I was able to host the file using lighttpd server.  I will open a new PR for including lighttpd in image.

**Comment by anselmolsm** [comment]
New PR: #231

**Pull request closed without merging**
