### PR TITLE
Update kernel to standard/intel/base branch

### PR DESCRIPTION
**Pull request by lucasdemarchi**
This updates our kernel to 4.4.60 and brings many features from upstream kernel that were backported.

It still needs some regression testing and the final config should be the same as it was before (check `/proc/config.gz` on both versions)

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
With some more commits I can reach a state in which it compiles, boots and basic functionality works.

Basing it off meta-intel is bringing a lot of config options that we don't want or care about, making this upgrade more difficult.

@whbruce here's the diff from before and after kernel bump:
https://hastebin.com/genuhilalu

Any idea how to get back the config I had?  We do want to take part of this diff, but I'd prefer to do it in steps: first bump kernel and after take the features that make sense for this project.

**Comment by whbruce** [comment]
@clsulliv it seems the move to meta-intel from genericx86 has introduced extra config settings. What's the best way of finding out what these are?

**Comment by lucasdemarchi** [comment]
I think my comment wasn't very clear. I know what's the diff by comparing /proc/config.gz before and after. I don't know how to force my old config though

**Comment by clsulliv** [comment]
You could force it via a defconfig.

http://www.yoctoproject.org/docs/2.2/mega-manual/mega-manual.html#creating-a-defconfig-file

---
Cal

**Comment by lucasdemarchi** [comment]
Now it should work properly. Tested:
* communication with FC on RTF
* usb-ethernet
* usb-host
* hostapd
* update from the updated image
* realsense

**Comment by lucasdemarchi** [comment]
It depends on https://github.com/intel-aero/intel-aero-manifest/pull/10 and a clean build is needed

**Pull request merged**
