### PR TITLE
Update iwlwifi-8000C firmware version to v19

### PR DESCRIPTION
**Pull request by avinash-palleti**
Updating firmware version as stability in hotspot connection is good compared
to existing v16.

Still Aero hotspot disconnection is observed but less when compared to 1.6.1 release.

### CODE REVIEW

**Comment by zehortigoza** [comment]
The v19 is probably present in the linux-firmware package why are you adding it? This way if there is a update in the v19 we are missing it unless you update the firmware binary again.

**Comment by avinash-palleti** [comment]
It is not there, it was removed with below commit.
http://cgit.openembedded.org/openembedded-core/commit/?id=bc36f8fd6afcbc4895b6ed0e91aedd240807f756

Instead of adding binary i will fetch it from https://git.kernel.org/cgit/linux/kernel/git/iwlwifi/linux-firmware.git/plain/iwlwifi-8000C-19.ucode

**Comment by zehortigoza** [comment]
If it was removed from poky and linux-firmware upstream it has problems and should not be used. Also I think we were using v19 in release v1.6 and we moved away from it because of instability problems too.

**Comment by avinash-palleti** [comment]
Yes it was the same reason why we migrated to v16, As it is sporadic issue it is so confusing to decide which one is stable. For sure this migration is not a fix for the issue as I observed issue even with v19.
But during my testing on 3 boards here, I felt issue is seen less often in v19 compared to v16.

**Comment by anselmolsm** [comment]
The issue is being investigated. Closing this for now.

**Pull request closed without merging**
